version: '3.1'

services:
  postgres:
    image: postgres:15.1
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env

  web:
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started

volumes:
  database:
  rubygems: